
version: '3.8'

services:
  fastapi:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - .:/app

  streamlit:
    build: 
      context: .
      dockerfile: Dockerfile_Streamlit
    ports:
      - "8501:8501"
    volumes:
      - .:/app
