
FROM python:3.8

WORKDIR /app

COPY requirements_streamlit.txt .

RUN pip install --no-cache-dir -r requirements_streamlit.txt

COPY . .

CMD ["streamlit", "run", "streamlit_app.py", "--server.port=8501"]
